# Testing reshaping demographic data using python

In [147]:
import pandas as pd
import numpy as np

In [148]:
demo = pd.read_csv("C:/Users/cangu/Documents/recess minutes 2025\cenroll2324.csv",
                   encoding='ISO-8859-1',
                   na_values = '*')

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\cangu\AppData\Local\Temp\ipykernel_20988\3108139213.py:1: SyntaxWarning: invalid escape sequence '\c'
  demo = pd.read_csv("C:/Users/cangu/Documents/recess minutes 2025\cenroll2324.csv",

In [149]:
demo.head()

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,CumulativeEnrollment
0,2023-24,C,1,NaN,NaN,Alameda,NaN,NaN,All,GF,106114.0
1,2023-24,C,1,NaN,NaN,Alameda,NaN,NaN,All,GM,113331.0
2,2023-24,C,1,NaN,NaN,Alameda,NaN,NaN,All,GX,323.0
3,2023-24,C,1,NaN,NaN,Alameda,NaN,NaN,All,RA,62208.0
4,2023-24,C,1,NaN,NaN,Alameda,NaN,NaN,All,RB,18433.0

In [150]:
# Keeping only school level data
demo = demo.loc[demo.AggregateLevel=='S']

# Creating cdscode variable
demo = demo.astype({'DistrictCode':'int64','SchoolCode':'int64'})
demo['cdscode'] = demo['CountyCode'].astype(str) + '' +  demo['DistrictCode'].astype(str) + '' + demo['SchoolCode'].astype(str)
demo = demo.astype({'cdscode':'int64'}) 
demo['ReportingCategory'] = demo['ReportingCategory'].astype('str')

# Keeping only necessary variables
demo = demo.drop(columns=['AcademicYear','AggregateLevel','CountyCode','DistrictCode','SchoolCode','Charter'])

## Race data

In [ ]:
race = demo[demo.ReportingCategory.str.startswith('R')]

,CountyName,DistrictName,SchoolName,ReportingCategory,CumulativeEnrollment,cdscode
44305,Alameda,Alameda County Office of Education,Alameda County Community,RA,NaN,110017130419
44306,Alameda,Alameda County Office of Education,Alameda County Community,RB,21.0,110017130419
44307,Alameda,Alameda County Office of Education,Alameda County Community,RD,NaN,110017130419
44308,Alameda,Alameda County Office of Education,Alameda County Community,RF,NaN,110017130419
44309,Alameda,Alameda County Office of Education,Alameda County Community,RH,86.0,110017130419